import './globals.css';
import { Poppins } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import AppBar from '@/components/layout/AppBar';

const font = Poppins({
    weight: ['100', '200', '300', '400', '500'],
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={font.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                >
                    <AppBar />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
